-- Ejecuta este archivo una sola vez en Supabase > SQL Editor.

create table if not exists public.libros (
  id bigint generated by default as identity primary key,
  titulo varchar(120) not null,
  autor varchar(120) not null,
  categoria varchar(30) not null,
  etiqueta varchar(40) not null,
  saga varchar(120) not null default 'Independiente',
  imagen text not null,
  valoracion numeric(2, 1) not null check (valoracion between 0 and 5),
  opinion varchar(1500) not null,
  puntos_destacados text[] not null default '{}',
  contiene_spoilers boolean not null default false,
  descripcion varchar(1500) not null,
  unique (titulo, autor)
);

create table if not exists public.administradores (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.libros enable row level security;
alter table public.administradores enable row level security;

create or replace function public.es_administrador()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.administradores
    where user_id = auth.uid()
  );
$$;

revoke all on function public.es_administrador() from public;
grant execute on function public.es_administrador() to authenticated;

drop policy if exists "Lectura pública de libros" on public.libros;
create policy "Lectura pública de libros"
on public.libros for select
using (true);

drop policy if exists "Administradores añaden libros" on public.libros;
create policy "Administradores añaden libros"
on public.libros for insert to authenticated
with check (public.es_administrador());

drop policy if exists "Administradores editan libros" on public.libros;
create policy "Administradores editan libros"
on public.libros for update to authenticated
using (public.es_administrador())
with check (public.es_administrador());

drop policy if exists "Administradores eliminan libros" on public.libros;
create policy "Administradores eliminan libros"
on public.libros for delete to authenticated
using (public.es_administrador());

drop policy if exists "Administrador consulta su permiso" on public.administradores;
create policy "Administrador consulta su permiso"
on public.administradores for select to authenticated
using (user_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'portadas',
  'portadas',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Lectura pública de portadas" on storage.objects;
create policy "Lectura pública de portadas"
on storage.objects for select
using (bucket_id = 'portadas');

drop policy if exists "Administradores suben portadas" on storage.objects;
create policy "Administradores suben portadas"
on storage.objects for insert to authenticated
with check (bucket_id = 'portadas' and public.es_administrador());

drop policy if exists "Administradores actualizan portadas" on storage.objects;
create policy "Administradores actualizan portadas"
on storage.objects for update to authenticated
using (bucket_id = 'portadas' and public.es_administrador())
with check (bucket_id = 'portadas' and public.es_administrador());

drop policy if exists "Administradores eliminan portadas" on storage.objects;
create policy "Administradores eliminan portadas"
on storage.objects for delete to authenticated
using (bucket_id = 'portadas' and public.es_administrador());

-- Copia inicial del catálogo actual. No duplica libros si vuelves a ejecutar el SQL.
insert into public.libros
  (titulo, autor, categoria, etiqueta, saga, imagen, valoracion, opinion,
   puntos_destacados, contiene_spoilers, descripcion)
values
  ('Alas de Sangre', 'Rebecca Yarros', 'fantasia', 'Fantasía', 'Empíreo',
   'img/alasdesangre-rosa.webp', 5,
   'Una lectura muy adictiva, con tensión constante y personajes que consiguen que quieras seguir leyendo.',
   array['Ritmo rápido', 'Dragones', 'Romance y tensión'], false,
   'Violet Sorrengail es forzada a unirse al brutal Colegio de Guerra de Basgiath para entrenar como jinete de dragón.'),
  ('Alas de Hierro', 'Rebecca Yarros', 'fantasia', 'Fantasía', 'Empíreo',
   'img/alasdehierro-rosa.webp', 5,
   'Mantiene la emoción de la primera parte y amplía el mundo, los conflictos y las relaciones entre los personajes.',
   array['Más acción', 'Evolución de Violet', 'Nuevos secretos'], false,
   'Continúan las pruebas de Violet para convertirse en jinete de dragón y su lucha contra los secretos del colegio.'),
  ('Alas de Ónix', 'Rebecca Yarros', 'fantasia', 'Fantasía', 'Empíreo',
   'img/alasdeonix-rosa.webp', 5,
   'Una continuación intensa que eleva el peligro y obliga a sus protagonistas a tomar decisiones difíciles.',
   array['Alianzas', 'Conflicto épico', 'Momentos emocionales'], false,
   'Violet debe defender su nación, buscar alianzas para la guerra y encontrar una cura para la transformación de Xaden.'),
  ('Etéreo', 'Joana Marcús', 'juveniles', 'Juvenil', 'Trilogía Extraños',
   'img/etereo-rosa.webp', 3,
   'Tiene una premisa interesante y personajes complejos, aunque algunas partes avanzan más despacio.',
   array['Poderes especiales', 'Personajes grises', 'Misterio'], false,
   'Caleb no es un chico corriente. Sus habilidades especiales y una vida complicada lo han llevado a trabajar para gente de moral dudosa.'),
  ('Ciudades de Humo', 'Joana Marcús', 'distopia', 'Distopía', 'Trilogía Fuego',
   'img/ciudadesdehumo-rosa.webp', 4,
   'Destaca por su mundo distópico y por la evolución de Alice mientras descubre qué significa vivir como humana.',
   array['Mundo distópico', 'Androides', 'Búsqueda de libertad'], false,
   'Alice, una androide, debe aprender a vivir como humana después de escapar de una existencia controlada.'),
  ('Ciudades de Ceniza', 'Joana Marcús', 'distopia', 'Distopía', 'Trilogía Fuego',
   'img/ciudadesdeceniza-rosa.webp', 4,
   'Una segunda parte con más acción y consecuencias, que continúa desarrollando el mundo de la trilogía.',
   array['Acción', 'Venganza', 'Evolución de Alice'], false,
   'Alice busca venganza tras la destrucción de su ciudad en un mundo de acción, romance, androides y experimentos prohibidos.'),
  ('Powerless', 'Lauren Roberts', 'fantasia', 'Fantasía', 'Powerless',
   'img/powerless-rosa.webp', 5,
   'Una fantasía muy entretenida, con pruebas peligrosas, rivalidad y una tensión romántica que sostiene la historia.',
   array['Pruebas', 'Rivalidad', 'Romance'], false,
   'Paedyn finge ser psíquica para sobrevivir en Ilya y acaba participando en las peligrosas Pruebas de la Purga.'),
  ('Powerful', 'Lauren Roberts', 'fantasia', 'Fantasía', 'Powerless',
   'img/powerful-rosa.webp', 4.5,
   'Una historia más breve y cercana que permite conocer mejor a Adena y aporta emoción al universo de la saga.',
   array['Adena y Mak', 'Lealtad', 'Historia complementaria'], false,
   'Adena y Mak afrontan peligrosos desafíos mientras desarrollan una relación marcada por la tensión, el romance y la lealtad.'),
  ('Reckless', 'Lauren Roberts', 'fantasia', 'Fantasía', 'Powerless',
   'img/reckless-rosa.webp', 4,
   'La persecución entre Paedyn y Kai mantiene la tensión, mientras ambos se enfrentan a lo que sienten y a su deber.',
   array['Persecución', 'Conflicto emocional', 'Tensión romántica'], false,
   'Paedyn huye después de matar al rey. Kai debe perseguirla, aunque se debate entre la lealtad, el deber y el deseo.'),
  ('Fearless', 'Lauren Roberts', 'fantasia', 'Fantasía', 'Powerless',
   'img/fearless-rosa.webp', 4,
   'Una entrega emocional que pone a prueba a los protagonistas y profundiza en el sacrificio y la redención.',
   array['Decisiones difíciles', 'Sacrificio', 'Redención'], false,
   'Paedyn y Kai se enfrentan a decisiones difíciles en una historia sobre el poder, el amor, el destino y la redención.'),
  ('Fearful', 'Lauren Roberts', 'fantasia', 'Fantasía', 'Powerless',
   'img/fearful-rosa.webp', 4,
   'Una mirada diferente al universo de Ilya, centrada en personajes y motivaciones que quedaban en segundo plano.',
   array['Nueva perspectiva', 'Kitt y Mara', 'Historia complementaria'], false,
   'Una decisión trascendental del rey lleva a Mara de vuelta a Ilya para tratar de comprender la mente de Kitt Azer.'),
  ('Blind Side', 'Kandi Steiner', 'romance', 'Romance', 'Red Zone Rivals',
   'img/blindside-rosa.webp', 3,
   'Un romance universitario ligero, con química entre los protagonistas y situaciones fáciles de disfrutar.',
   array['Romance deportivo', 'Universidad', 'Química'], false,
   'Una coordinadora de relaciones públicas debe lidiar con Clay Johnson después de que una ruptura lo convierta en su mayor dolor de cabeza.')
on conflict (titulo, autor) do nothing;
