-- Ejecuta este archivo una sola vez en:
-- Supabase > SQL Editor > New query

create table if not exists public.recomendaciones (
  id bigint generated by default as identity primary key,
  titulo varchar(100) not null,
  autor varchar(100) not null,
  nombre varchar(80) not null,
  email varchar(254) not null,
  comentario varchar(1000) not null,
  consentimiento boolean not null check (consentimiento = true),
  estado varchar(10) not null default 'pendiente'
    check (estado in ('pendiente', 'aprobada', 'rechazada'))
);

-- Nadie puede consultar los correos desde el navegador.
-- La función privada de Vercel utiliza la clave service_role.
alter table public.recomendaciones enable row level security;

comment on table public.recomendaciones is
  'Recomendaciones privadas enviadas desde Camelia Books';
