const libros=[
['Alas de Sangre','Rebecca Yarros','fantasia','Fantasía','alasdesangrewhite.jpeg',5,'Violet Sorrengail es forzada a unirse al brutal Colegio de Guerra de Basgiath para entrenar como jinete de dragón.'],
['Alas de Hierro','Rebecca Yarros','fantasia','Fantasía','alasdehierro.jpg',5,'Continúan las pruebas de Violet para convertirse en jinete de dragón y su lucha contra los secretos del colegio.'],
['Alas de Ónix','Rebecca Yarros','fantasia','Fantasía','alasdeonixwhite.jpg',5,'Violet debe defender su nación, buscar alianzas para la guerra y encontrar una cura para la transformación de Xaden.'],
['Etéreo','Joana Marcús','juveniles','Juvenil','etereo.jpg',3,'Caleb no es un chico corriente. Sus habilidades especiales y una vida complicada lo han llevado a trabajar para gente de moral dudosa.'],
['Ciudades de Humo','Joana Marcús','distopia','Distopía','ciudadesdehumo.jpg',4,'Alice, una androide, debe aprender a vivir como humana después de escapar de una existencia controlada.'],
['Ciudades de Ceniza','Joana Marcús','distopia','Distopía','ciudadesdeceniza.jpg',4,'Alice busca venganza tras la destrucción de su ciudad en un mundo de acción, romance, androides y experimentos prohibidos.'],
['Powerless','Lauren Roberts','fantasia','Fantasía','Powerless.webp',5,'Paedyn finge ser psíquica para sobrevivir en Ilya y acaba participando en las peligrosas Pruebas de la Purga.'],
['Powerful','Lauren Roberts','fantasia','Fantasía','powerful.webp',4.5,'Adena y Mak afrontan peligrosos desafíos mientras desarrollan una relación marcada por la tensión, el romance y la lealtad.'],
['Reckless','Lauren Roberts','fantasia','Fantasía','reckless.webp',4,'Paedyn huye después de matar al rey. Kai debe perseguirla, aunque se debate entre la lealtad, el deber y el deseo.'],
['Fearless','Lauren Roberts','fantasia','Fantasía','fearless.jpg',4,'Paedyn y Kai se enfrentan a decisiones difíciles en una historia sobre el poder, el amor, el destino y la redención.'],
['Fearful','Lauren Roberts','fantasia','Fantasía','fearful.jpg',4,'Una decisión trascendental del rey lleva a Mara de vuelta a Ilya para tratar de comprender la mente de Kitt Azer.'],
['Blind Side','Kandi Steiner','romance','Romance','blindside.jpg',3,'Una coordinadora de relaciones públicas debe lidiar con Clay Johnson después de que una ruptura lo convierta en su mayor dolor de cabeza.']
].map(([titulo,autor,categoria,etiqueta,imagen,rating,descripcion])=>({titulo,autor,categoria,etiqueta,imagen:`img/${imagen}`,rating,descripcion}));
const lista=document.querySelector('#lista-libros'),buscador=document.querySelector('#buscador-libros'),limpiar=document.querySelector('#limpiar-buscador'),contador=document.querySelector('#contador-resultados'),vacio=document.querySelector('#sin-resultados'),botones=[...document.querySelectorAll('[data-categoria]')];let categoria='todas';
const normalizar=t=>t.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function estrellas(n){return `<span class="estrellas" role="img" aria-label="${n} de 5 estrellas"><span aria-hidden="true">★★★★★</span><span class="estrellas-relleno" style="width:${n/5*100}%" aria-hidden="true">★★★★★</span></span>`}
function tarjeta(l,i){return `<article class="libro-contenedor"><div class="libro-imagen"><img src="${l.imagen}" alt="Portada de ${l.titulo}" loading="lazy"><span class="categoria">${l.etiqueta}</span></div><div class="libro-info"><div><p class="numero">Lectura ${String(i+1).padStart(2,'0')}</p><h3>${l.titulo}</h3><p class="autor">${l.autor}</p><p class="descripcion" id="descripcion-${i}">${l.descripcion}</p></div><div class="valoracion"><div><span class="valoracion-texto">Valoración</span>${estrellas(l.rating)}</div><button class="leer-mas" type="button" aria-expanded="false" aria-controls="descripcion-${i}"><span>Leer más</span><span class="flecha" aria-hidden="true">⌄</span></button></div></div></article>`}
function render(){const q=normalizar(buscador.value.trim()),visibles=libros.filter(l=>(categoria==='todas'||l.categoria===categoria)&&normalizar(`${l.titulo} ${l.autor}`).includes(q));lista.innerHTML=visibles.map(l=>tarjeta(l,libros.indexOf(l))).join('');contador.textContent=`${visibles.length} ${visibles.length===1?'libro':'libros'}`;vacio.hidden=visibles.length!==0;limpiar.classList.toggle('visible',buscador.value.length>0)}
botones.forEach(b=>b.addEventListener('click',()=>{categoria=b.dataset.categoria;botones.forEach(x=>x.classList.toggle('activo',x===b));render()}));buscador.addEventListener('input',render);limpiar.addEventListener('click',()=>{buscador.value='';buscador.focus();render()});lista.addEventListener('click',e=>{const b=e.target.closest('.leer-mas');if(!b)return;const d=document.getElementById(b.getAttribute('aria-controls')),abierta=d.classList.toggle('expandida');b.setAttribute('aria-expanded',abierta);b.querySelector('span').textContent=abierta?'Leer menos':'Leer más'});document.querySelector('#anio').textContent=new Date().getFullYear();render();
